# Generated by Django 4.1.2 on 2022-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
