# Generated by Django 4.0.3 on 2022-11-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(default='12'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(default='12'),
        ),
    ]
