# Generated by Django 4.1.3 on 2022-11-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_end_time_post_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(max_length=30, null='True'),
        ),
    ]
